### ISSUE TITLE
Fail to run dev server

### ISSUE THREAD

**Issue by ayming** [jamesknelson/webpack-black-triangle#1]
```
// package.json
"scripts": {
  "start": "node_modules/webpack-dev-server/bin/webpack-dev-server.js"
}
```

Are you missing `node` command to run the script?

**Comment by jamesknelson** [comment]
@ayming This works on my machine. What version of node/npm are you using?

**Comment by karataev** [comment]
Same for me on windows

> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> npm ERR! node v6.3.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! webpack-black-triangle@0.1.0 start: `node_modules/webpack-dev-server/bin/webpack-dev-server.js`
> npm ERR! Exit status 1

Adding `node` command solves the problem.

**Comment by draperd** [comment]
I'm having issues as well. I'm on a Linux environment and have tried both Node 6.0.0 and Node 6.6.0. I've also tried updating the the package.json file to include the node command.

When running `npm install` I see:

> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

When starting up I see:

> > webpack-black-triangle@0.1.0 start /home/dave/Experiments/webpack-black-triangle-master
> > node_modules/webpack-dev-server/bin/webpack-dev-server.js
> 
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE 127.0.0.1:8080
>     at Object.exports._errnoException (util.js:896:11)
>     at exports._exceptionWithHostPort (util.js:919:20)
>     at Server._listen2 (net.js:1246:14)
>     at listen (net.js:1282:10)
>     at net.js:1392:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:65:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:84:10)
> 
> npm ERR! Linux 4.4.0-38-generic
> npm ERR! argv "/home/dave/.nvm/versions/node/v6.0.0/bin/node" "/home/dave/.nvm/versions/node/v6.0.0/bin/npm" "start"
> npm ERR! node v6.0.0
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> npm ERR! webpack-black-triangle@0.1.0 start: `node_modules/webpack-dev-server/bin/webpack-dev-server.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the webpack-black-triangle@0.1.0 start script 'node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the webpack-black-triangle package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node_modules/webpack-dev-server/bin/webpack-dev-server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs webpack-black-triangle
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls webpack-black-triangle
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/dave/Experiments/webpack-black-triangle-master/npm-debug.log

What version of Node would you recommend be used?
